name: Release Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '31.0.0'
          ndk-version: '23.1.7779620'
          android-platform: 'android-19'

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Set up gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

      - name: Build AndroidLibXrayLite
        run: |
          echo "RELEASE_VERSION=v$(date '+%Y-%m-%d')-release" >> $RUNNER_TEMP/release.env
          echo "================================================"
          echo "================================================"
          echo "================================================"
          ls 
          go mod tidy -v
          echo "================================================"
          echo "================================================"
          echo "================================================"
          ls          
          gomobile bind -v -androidapi 19 -ldflags='-s -w' -o=./libxraylite.aar ./
          echo "================================================"
          echo "================================================"
          ls  
          echo "================================================"
      - name: upload to bashupload
        run: |
          echo "================================================"
          curl bashupload.com -T libxraylite.aar
          curl bashupload.com -T ./libxraylite.aar
          echo "================================================"

      - name: Upload files to Artifacts t2
        uses: actions/upload-artifact@v3
        with:
          name: libxraylite.aar
          path: |
            ./libxraylite.aar

      - name: Upload binaries to release t2
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          file: ./libxraylite.aar
          tag: ${{ github.ref }}
          file_glob: true
