name: Release Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '31.0.0'
          ndk-version: '23.1.7779620'
          android-platform: 'android-19'

      - name: Set up gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          echo "y" | gomobile init

      - name: Build AndroidLibXrayLite
        run: |
          echo "RELEASE_VERSION=v$(date '+%Y-%m-%d')-release" >> $RUNNER_TEMP/release.env
          echo "================================================"
          echo "================================================"
          echo "================================================"
          ls 
          go mod tidy -v
          echo "================================================"
          echo "================================================"
          echo "================================================"
          ls          
          gomobile bind -v -androidapi 19 -ldflags='-s -w' -o=./build/libxraylite.aar ./

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release:
            - First change
            - Second change
          draft: false
          prerelease: false

      - name: Upload Asset
        id: upload_asset
        uses: actions/upload-release-asset@v1
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libxraylite.aar
