name: Build AndroidLibXrayLite and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-version: '31.0.0'
        ndk-version: '23.1.7779620'
        android-platform: 'android-19'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19'

    - name: Set up gomobile
      run: go install golang.org/x/mobile/cmd/gomobile@latest

    - name: Build AndroidLibXrayLite
      run: |
        echo "================================================"
        echo "================================================"
        echo "================================================"
        echo "================================================"
        ls
        echo "================================================"
        echo "================================================"
        echo "================================================"
        ls
        gomobile init
        go mod tidy -v
        mkdir build
        gomobile bind -v -androidapi 19 -ldflags='-s -w' ./
        echo "================================================"
        echo "================================================"
        echo "================================================"
        echo "================================================"
        ls
        echo "================================================"
        echo "================================================"
        echo "================================================"
        echo "================================================"
        ls
        echo "================================================"
        echo "================================================"
        echo "================================================"
        echo "================================================"

    - name: Set Release Version
      run: echo "RELEASE_VERSION=v$(date '+%Y-%m-%d')-release" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: libv2ray
        path: libv2ray.aar

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELESE_TOKEN }}
      with:
        artifacts: |
          libv2ray
        body: |
          This is a test release.
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: ${{ env.RELEASE_VERSION }}
