name: Build and release Xray Lite for Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Set up gomobile
        run: go install golang.org/x/mobile/cmd/gomobile@latest

      - name: Build AndroidLibXrayLite
        run: |
          gomobile init
          echo "RELEASE_VERSION=v$(date '+%Y-%m-%d')-release" >> $RUNNER_TEMP/release.env
          go mod tidy -v
          mkdir build
          gomobile bind -v -target=android -tags=jsoniter -o build/libxraylite.aar ./
          cp $RUNNER_TEMP/release.env ./build/release.env

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          RELEASE_VERSION: ${{ secrets.RELEASE_VERSION }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}
          body: |
            Changes in this release:
            - First change
            - Second change
          draft: false
          prerelease: false

      - name: Upload Asset
        id: upload_asset
        uses: actions/upload-release-asset@v1
        env:
          RELEASE_VERSION: ${{ secrets.RELEASE_VERSION }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libxraylite.aar
          asset_name: libxraylite.aar
          asset_content_type: application/octet-stream
