name: Build AndroidLibXrayLite

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-version: '31.0.0'
        ndk-version: '23.1.7779620'
        android-platform: 'android-19'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Set up gomobile
      run: go install golang.org/x/mobile/cmd/gomobile@latest

    - name: Build AndroidLibXrayLite
      run: |
        cd AndroidLibXrayLite
        gomobile init
        go mod tidy -v
        gomobile bind -v -androidapi 19 -ldflags='-s -w' ./
